# Generated by Django 3.1.1 on 2020-09-10 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vm',
            options={'ordering': ('-created_date',)},
        ),
    ]
